FROM mcr.microsoft.com/devcontainers/miniconda:3

RUN conda install -n base -c conda-forge mamba

# Here we can install all the dependencies using mamba (as we do in the test scripts)

COPY .devcontainer/uw_environment.yml  /tmp/conda-tmp/
RUN  mamba env update -n base --file /tmp/conda-tmp/uw_environment.yml 
